---
- name: Check CPU Load Average
  hosts: all
  gather_facts: true

  vars:
    load_warning_threshold: 0.8

  tasks:
    - name: Display CPU information
      debug:
        msg:
          - "CPU Cores: {{ ansible_processor_cores }}"
          - "1-minute Load Average: {{ ansible_loadavg.0 }}"
          - "Load per Core: {{ (ansible_loadavg.0 / ansible_processor_cores) | float | round(2) }}"

    - name: Check CPU load status
      debug:
        msg: "{{ (ansible_loadavg.0 / ansible_processor_cores) > load_warning_threshold | ternary('WARNING: Load is high!', 'OK: Load is normal') }}"
