---
- name: Check CPU Load Average
  hosts: all
  gather_facts: true

  vars:
    load_warning_threshold: 0.8

  tasks:
    - name: Get load average safely
      shell: |
        timeout 5s cat /proc/loadavg 2>/dev/null | awk '{print $1}' || echo "0"
      register: load_result
      changed_when: false

    - name: Set load average fact
      set_fact:
        one_min_load: "{{ load_result.stdout | float }}"

    - name: Display CPU information
      debug:
        msg:
          - "CPU Cores: {{ ansible_processor_cores }}"
          - "1-minute Load Average: {{ one_min_load }}"
          - "Load per Core: {{ (one_min_load / ansible_processor_cores) | round(2) }}"

    - name: Check CPU load status
      debug:
        msg: "{{ ((one_min_load / ansible_processor_cores) > load_warning_threshold) | ternary('WARNING: Load is high!', 'OK: Load is normal') }}"
