---
- name: Check System Memory Usage
  hosts: all
  gather_facts: true

  vars:
    memory_warning_threshold_mb: 100  # Warn if free memory < 100MB

  tasks:
    - name: Display memory information
      debug:
        msg:
          - "Total Memory: {{ ansible_memtotal_mb }} MB"
          - "Free Memory: {{ ansible_memfree_mb }} MB"
          - "Memory Usage: {{ ((ansible_memtotal_mb - ansible_memfree_mb) / ansible_memtotal_mb * 100) | round(2) }}%"

    - name: Check if free memory is critically low
      fail:
        msg: "CRITICAL: Free memory ({{ ansible_memfree_mb }} MB) is below threshold of {{ memory_warning_threshold_mb }} MB!"
      when: ansible_memfree_mb < memory_warning_threshold_mb

    - name: Memory status OK
      debug:
        msg: "OK: Free memory ({{ ansible_memfree_mb }} MB) is sufficient."
      when: ansible_memfree_mb >= memory_warning_threshold_mb
